### ISSUE TITLE
Ansible-shell not support Ansible modules 

### ISSUE THREAD

**Issue by canshen-yottaa** [dominis/ansible-shell#35]
Ansible verison:  Ansible 1.8

After ansible 1.8  version has cancel the library_path vaule at ansible.cfg. 
at ansible-shell interaction model not display ansible module when I type TAB.

**Comment by dominis** [comment]
should be fixed by #31, please pull master and try it out

**Comment by canshen-yottaa** [comment]
Thank You very much
