### ISSUE TITLE
update release on pypi

### ISSUE THREAD

**Issue by gimoh** [dominis/ansible-shell#45]
Hi, could you push a new release to PyPI when you get a chance? The one currently there is old and crashes on startup.

**Comment by dominis** [comment]
i'm working on fixing the pypi deployment from travis ci

**Comment by dominis** [comment]
i've just fixed the issue in: d19d661640fd48c3f420cf863ea81e92573d3a46 and published the latest master to pypi

**Comment by gimoh** [comment]
Thanks!
