### ISSUE TITLE
host-pattern is ignored

### ISSUE THREAD

**Issue by xiongchiamiov** [dominis/ansible-shell#48]
My understanding is that `ansible-shell some-pattern` should launch a shell that only runs commands on hosts matching that pattern; however, it seems to still run commands against _all_ hosts.

From a very brief glance over the code, it looks like this information is just ignored and never picked up during the argument parsing.

**Comment by dominis** [comment]
thanks for bringing this up, IIRC this was never worked but this is the way ansible handles args so I'll look into this issue.
