### ISSUE TITLE
Incompatible with Ansible 2.0

### ISSUE THREAD

**Issue by xiongchiamiov** [dominis/ansible-shell#50]
Ansible 2.0 just dropped this week.  With it, I get this error:

```
[$]> ansible-shell                                                                                                                                                                                              
Traceback (most recent call last):
  File "/usr/bin/ansible-shell", line 36, in <module>
    import ansible.runner
ImportError: No module named runner
```

I don't see any mention of a re-org of `runner` in [the changelog](https://github.com/ansible/ansible/blob/devel/CHANGELOG.md), but it has definitely moved (or disappeared).

**Comment by dominis** [comment]
I've just realized they released 2.0. I'll try to find some time and fix this asap

**Comment by xiongchiamiov** [comment]
I'm subscribed to [ansible-announce](https://groups.google.com/forum/#!forum/ansible-announce), so that's the main reason I saw it.  And then the package upgraded in Arch, and that's when I realized this was broken. :)

Let me know if it'd be useful for me to spend a day or something digging into this; I can probably allocate some time in about two weeks.

**Comment by evgkrsk** [comment]
ping?
