### ISSUE TITLE
how to use console.py of official ansible 2.1

### ISSUE THREAD

**Issue by rolandjohann** [dominis/ansible-shell#52]
At the README you stated that the functionality of this application will be available at ansible 2.1 but I can't find anything regarding that. I know that one can execute ansible modules via command line but that's not as convenient as your application.
Can you give any hints regarding that?

**Comment by rmmjohann** [comment]
Found the hint at a git PR https://github.com/ansible/ansible/pull/14824

**Comment by tamsky** [comment]
It wasn't obvious to me either.

`ansible-console --help` should go into our README.
